name: Vix
main: com.onemoreblock.oml.Vix
version: 0.2.1
commands:
   create:
      description: Create level
      usage: /create <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   play:
      description: Play a level
      usage: /play <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   edit:
      description: Edit a level
      usage: /edit <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   delete:
      description: Delete a level
      usage: /delete <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   exit:
      description: Leave the level
      usage: /exit
      permission: vix.basic
      permission-message: You don't have <permission>