name: Vix
main: com.onemoreblock.oml.Vix
version: 0.2.1
commands:
   create:
      description: Create level
      usage: /create <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   play:
      description: Play a level
      usage: /play <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   edit:
      description: Edit a level
      usage: /edit <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   delete:
      description: Delete a level
      usage: /delete <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   confirm:
      description: Confirm a command
      usage: /confirm
      permission: vix.basic
      permission-message: You don't have <permission>
   setleavepoint:
      description: Set the spawn
      usage: /setleavepoint
      permission: vix.admin
      permission-message: You don't have <permission>
   leave:
      description: Leave the level
      usage: /leave
      permission: vix.basic
      permission-message: You don't have <permission>
   setstart:
      description: Set the beginning of your level
      usage: /setstart
      permission: vix.basic
      permission-message: You don't have <permission>
   publish:
      description: Publish your level
      usage: /publish <name>
      permission: vix.basic
      permission-message: You don't have <permission>
   reset:
      description: resets
      usage: /reset
      permission: vix.admin
      permission-message: You don't have <permission>